# Generated by Django 3.1.7 on 2021-03-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('country_iso', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('subdivisions', models.CharField(max_length=255)),
                ('subdivisions_iso', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal', models.CharField(max_length=255)),
                ('lng', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=255)),
            ],
        ),
    ]
