# Generated by Django 3.1.7 on 2021-03-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthehacker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerinfo',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hackerinfo',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hackerinfo',
            name='country_iso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hackerinfo',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hackerinfo',
            name='lng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hackerinfo',
            name='postal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hackerinfo',
            name='subdivisions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hackerinfo',
            name='subdivisions_iso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
